config/routes.rb
Rails.application.routes.draw do
  get 'page/index'

  resources :animes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anime.rb
class Anime < ApplicationRecord
    
    
    def suma
     sum = self.numero.to_i + Anime.count.to_i 
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :set_anime, only: [:show, :edit, :update, :destroy]

  # GET /animes
  # GET /animes.json
  def index
    @animes = Anime.all
  end

  # GET /animes/1
  # GET /animes/1.json
  def show
  end

  # GET /animes/new
  def new
    @anime = Anime.new
      respond_to do |format|
        format.js
      end
    
  end

  # GET /animes/1/edit
  def edit
  end

  # POST /animes
  # POST /animes.json
  def create
    @anime = Anime.new(anime_params)
     @animes = Anime.all
    respond_to do |format|
      if @anime.save
        format.html { redirect_to @anime, notice: 'Anime was successfully created.' }
        format.json { render :show, status: :created, location: @anime }
        format.js
      else
        format.html { render :new }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animes/1
  # PATCH/PUT /animes/1.json
  def update
    respond_to do |format|
      if @anime.update(anime_params)
        format.html { redirect_to @anime, notice: 'Anime was successfully updated.' }
        format.json { render :show, status: :ok, location: @anime }
      else
        format.html { render :edit }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animes/1
  # DELETE /animes/1.json
  def destroy
    @anime.destroy
    respond_to do |format|
      format.html { redirect_to animes_url, notice: 'Anime was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anime
      @anime = Anime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anime_params
      params.require(:anime).permit(:nombre, :numero)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/animes/_fila.html.erb
    <tr id="<%= anime.id %>">
        <td><%= anime.nombre %></td>
        <td><%= anime.numero %></td>
        <td><%= anime.suma %></td>
        <td><%= link_to 'Show', anime %></td>
        <td><%= link_to 'Edit', edit_anime_path(anime) %></td>
        <td><%= link_to 'Destroy', anime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>

app/views/animes/_form.html.erb
<%= form_for(@anime, remote: true) do |f| %>


  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :numero %>
    <%= f.number_field :numero %>
  </div>

  <div class="actions">
    <%= f.submit 'guardar nime' %>
  </div>
<% end %>

app/views/animes/create.js.erb
$('#cuerpo').append('<%= j render "/animes/fila", anime: @anime %>');


$('#count').html('Animes disponibles: <%= Anime.count %>')

app/views/animes/edit.html.erb
<h1>Editing Anime</h1>

<%= render 'form', anime: @anime %>

<%= link_to 'Show', @anime %> |
<%= link_to 'Back', animes_path %>

app/views/animes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Animes</h1>

<div id="count">Animes disponibles: <%= Anime.count %></div>
<div id="formulario"></div>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Numero</th>
      <th>Suma</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="cuerpo">
    <% @animes.each do |anime| %>
    
      <%= render 'animes/fila', anime: anime %>
    
      
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Anime', new_anime_path, remote: true %>

app/views/animes/new.html.erb
<h1>New Anime</h1>

<%= render 'form', anime: @anime %>

<%= link_to 'Back', animes_path %>

app/views/animes/new.js.erb
$('#formulario').html('<%= j render 'form', anime: @anime %>')

app/views/animes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @anime.nombre %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @anime.numero %>
</p>

<%= link_to 'Edit', edit_anime_path(@anime) %> |
<%= link_to 'Back', animes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeInteractive</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/index.html.erb
<footer>
    <p>HOLA MUNDO</p>
</footer>